/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddEmployeePayload { 'name' : string, 'employeeId' : string }
export interface AttendanceEntry { 'status' : string, 'date' : string }
export interface Employee {
  'leavesUsed' : bigint,
  'name' : string,
  'employeeId' : string,
  'attendanceHistory' : Array<AttendanceEntry>,
  'leavesRemaining' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEmployee' : ActorMethod<[AddEmployeePayload], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAttendanceHistory' : ActorMethod<[string], Array<AttendanceEntry>>,
  'getCallerEmployeeId' : ActorMethod<[], string>,
  'getCallerEmployeeName' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployee' : ActorMethod<[string], Employee>,
  'getMarkToday' : ActorMethod<[string, string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[string, string, string], undefined>,
  'overrideAttendance' : ActorMethod<[string, string, string], undefined>,
  'registerEmployeeMapping' : ActorMethod<[string], undefined>,
  'removeEmployee' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];