/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AddEmployeePayload = IDL.Record({
  'name' : IDL.Text,
  'employeeId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AttendanceEntry = IDL.Record({
  'status' : IDL.Text,
  'date' : IDL.Text,
});
export const Employee = IDL.Record({
  'leavesUsed' : IDL.Nat,
  'name' : IDL.Text,
  'employeeId' : IDL.Text,
  'attendanceHistory' : IDL.Vec(AttendanceEntry),
  'leavesRemaining' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmployee' : IDL.Func([AddEmployeePayload], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAttendanceHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceEntry)],
      ['query'],
    ),
  'getCallerEmployeeId' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerEmployeeName' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployee' : IDL.Func([IDL.Text], [Employee], ['query']),
  'getMarkToday' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'overrideAttendance' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'registerEmployeeMapping' : IDL.Func([IDL.Text], [], []),
  'removeEmployee' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AddEmployeePayload = IDL.Record({
    'name' : IDL.Text,
    'employeeId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AttendanceEntry = IDL.Record({
    'status' : IDL.Text,
    'date' : IDL.Text,
  });
  const Employee = IDL.Record({
    'leavesUsed' : IDL.Nat,
    'name' : IDL.Text,
    'employeeId' : IDL.Text,
    'attendanceHistory' : IDL.Vec(AttendanceEntry),
    'leavesRemaining' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmployee' : IDL.Func([AddEmployeePayload], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAttendanceHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceEntry)],
        ['query'],
      ),
    'getCallerEmployeeId' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerEmployeeName' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployee' : IDL.Func([IDL.Text], [Employee], ['query']),
    'getMarkToday' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'overrideAttendance' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'registerEmployeeMapping' : IDL.Func([IDL.Text], [], []),
    'removeEmployee' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };